<?php
/**
 * RARLinks Stats Dashboard
 *
 * Refactored to delegate filter logic to Cogito_RAR_Dashboard_Filters.
 */

if ( ! defined( 'ABSPATH' ) ) exit;

class Cogito_RAR_Dashboard {

	public static function init() {
		add_action( 'admin_menu', [ self::class, 'add_dashboard_page' ] );
	}

	public static function add_dashboard_page() {
		add_submenu_page(
			'edit.php?post_type=rar_redirect',
			'RARLinks Stats',
			'View Clicks',
			'manage_options',
			'rar_dashboard',
			[ self::class, 'render_dashboard' ]
		);
	}

	public static function render_dashboard() {
		global $wpdb;

		$table = esc_sql( $wpdb->prefix . 'rarlinks_clicks' ); // Secure table name

		// 1. 🧹 Delegate Input Handling & SQL Generation
		// We no longer manually parse $_GET here. The helper class does it all.
		$filters = Cogito_RAR_Dashboard_Filters::get_filters();

		// Build the SQL WHERE string for the total count query
		$date_filter_sql = '';
		if ( $filters ) {
			$date_filter_sql = 'WHERE ' . implode( ' AND ', $filters );
		}

		// 2. 🕓 Determine earliest click date (Required for the Filter UI date picker)
		// We still need to calculate this to pass it to the render method.
		$params = Cogito_RAR_Dashboard_Filters::get_params(); // Get sanitized params for post_id check
		
		if ( ! is_null( $params['post_id'] ) ) {
			$min_date_sql = $wpdb->prepare(
				"SELECT MIN(DATE(CONVERT_TZ(timestamp, 'America/Los_Angeles', 'Europe/London'))) 
				 FROM $table 
				 WHERE post_id = %d",
				$params['post_id']
			);
		} else {
			$min_date_sql = "SELECT MIN(DATE(CONVERT_TZ(timestamp, 'America/Los_Angeles', 'Europe/London'))) FROM $table";
		}
		
		$min_date = $wpdb->get_var( $min_date_sql );

		// 3. 📈 Get filtered chart data (delegated to chart classes)
		// 🟢 CRITICAL: Charts use the EXACT same $filters array as the table below.
		$chart = Cogito_RAR_Line_Chart::get_data( $filters );
		
		// If only one data point, visually pad the chart
		if ( count( $chart['data'] ) === 1 ) {
			$chart['labels'] = [ '', $chart['labels'][0], '' ];
			$chart['data']   = [ null, $chart['data'][0], null ];
		}
		
		// 🍩 Get filtered data for doughnut chart
		$doughnut = Cogito_RAR_Doughnut_Chart::get_data( $filters );

		// Prepare chart data for JS
		$chart_data_to_localize = [
			'line'     => $chart,
			'doughnut' => $doughnut
		];
		
		wp_localize_script(
			'rar-charts-js',
			'rarChartData',
			$chart_data_to_localize
		);

		// 4. 🔢 Fetch total count based on current filters
		$count_sql    = "SELECT COUNT(*) FROM $table $date_filter_sql";
		$total_items  = (int) $wpdb->get_var( $count_sql );
		$total_clicks = $total_items;

		// 5. 🖥️ Output UI
		echo '<div class="wrap rar_stat-sdash">';
		echo '<h1>RARLinks Clicks</h1>';
		echo '<h2>Total Clicks: ' . number_format( $total_clicks ) . '</h2>';

		// Summary Logic (Render text "Showing clicks for...")
		self::render_summary_text( $params );

		echo '<div style="max-width: 100%; margin-bottom: 40px;">';
		
		// Charts Container
		echo '<div style="display: flex; flex-wrap: wrap; gap: 30px; margin-bottom: 40px;">';
			// Line Chart
			echo '<div style="flex: 1 1 70%; min-width: 300px;">';
			echo '<h2>Clicks Over Time</h2>';
			echo '<canvas id="rarLineChart"></canvas>';
			echo '</div>';
			
			// Doughnut Chart (Hide on individual post view)
			if ( is_null( $params['post_id'] ) ) {
				echo '<div style="flex: 1 1 22%;">';
				echo '<h2>Top Ten Links</h2>';
				echo '<canvas id="rarDoughnutChart" height="300"></canvas>';
				echo '</div>';
			}
		echo '</div>';

		// 6. 🎛️ Render Unified Filter Form (Delegated)
		Cogito_RAR_Dashboard_Filters::render( $min_date );

        // 6b. 🏍️ Render Moto Partner management panel
        Cogito_RAR_Moto_Partner_Panel::render();

		// 7. 📋 Render List Table
		// 🟢 CRITICAL: List Table uses the EXACT same $filters array as the charts above.
		$list_table = new Cogito_RAR_Clicks_List_Table( $filters );
		$list_table->prepare_items();
		
		?>
		<div class="rarlinks-table-wrapper"> 
			<form method="get">
				<input type="hidden" name="post_type" value="rar_redirect" />
				<input type="hidden" name="page" value="rar_dashboard" />
				<?php
					// We must manually preserve traffic_type and date params here 
					// so pagination links generated by WP_List_Table include them.
					if ( ! empty( $params['traffic_type'] ) ) {
						echo '<input type="hidden" name="traffic_type" value="' . esc_attr( $params['traffic_type'] ) . '" />';
					}
					if ( ! empty( $params['range'] ) ) {
						echo '<input type="hidden" name="range" value="' . esc_attr( $params['range'] ) . '" />';
					}
					if ( ! empty( $params['from'] ) ) {
						echo '<input type="hidden" name="from" value="' . esc_attr( $params['from'] ) . '" />';
					}
					if ( ! empty( $params['to'] ) ) {
						echo '<input type="hidden" name="to" value="' . esc_attr( $params['to'] ) . '" />';
					}
					if ( ! is_null( $params['post_id'] ) ) {
						echo '<input type="hidden" name="post_id" value="' . $params['post_id'] . '" />';
					}

					$list_table->views();
					$list_table->display();
				?>
			</form>
		</div>
		<?php
			
		echo '</div>'; // End wrap
	}

	/**
	 * Helper to render the text summary ("Showing clicks for Today...")
	 * @param array $params
	 */
	private static function render_summary_text( $params ) {
		$range_msg = '<p><strong>Showing clicks';
		
		if ( ! is_null( $params['post_id'] ) ) {
			$post_obj = get_post( $params['post_id'] );
			if ( $post_obj ) {
				$range_msg .= ' for: <strong><span style="font-weight:600;">' . esc_html( $post_obj->post_title ) . '</span></strong>';
			}
		}
		
		$fmt = function($date) {
			$d = DateTime::createFromFormat('Y-m-d', $date);
			return $d ? $d->format('D, d M Y') : $date;
		};
		
		$now = new DateTime();
		$range = $params['range'];
		$from  = $params['from'];
		$to    = $params['to'];
		
		if ( $range ) {
			$format_date = fn($d) => $d->format('D, d M Y');
			switch ($range) {
				case 'today': $label = 'Today: ' . $format_date($now); break;
				case 'yesterday': $label = 'Yesterday: ' . $format_date((clone $now)->modify('-1 day')); break;
				case '7days': $label = 'Last 7 Days'; break;
				case '14days': $label = 'Last 14 Days'; break;
				case '30days': $label = 'Last 30 Days'; break;
				case 'thismonth': $label = 'This Month'; break;
				case 'lastmonth': $label = 'Last Month'; break;
				case 'all': $label = 'All Time'; break;
				default: $label = '';
			}
			if ( $label ) $range_msg .= ' for ' . $label;
		}

		if ( $from && $to ) {
			$range_msg .= ' from ' . $fmt($from) . ' to ' . $fmt($to);
		} elseif ( $from && !$to ) {
			$range_msg .= ' from ' . $fmt($from) . ' to ' . $now->format('D, d M Y');
		} elseif ( !$from && $to ) {
			$range_msg .= ' on ' . $fmt($to);
		}
		
		if ( empty($range) && empty($from) && empty($to) ) {
    $start = (clone $now)->modify('-30 days');
    // Only show year on start date if it differs from the end date's year
    $start_format = $start->format('Y') !== $now->format('Y') ? 'd M Y' : 'd M';
    $range_msg .= ' for the last 30 days: ' . $start->format($start_format) . ' to ' . $now->format('d M Y');
}

		// Traffic Type Annotation
		if ( $params['traffic_type'] === 'human' ) $range_msg .= ' (Human Only)';
		if ( $params['traffic_type'] === 'bots' ) $range_msg .= ' (Bots Only)';
		
		if ( ! is_null( $params['post_id'] ) ) {
			$base_url = remove_query_arg('post_id');
			$range_msg .= ' &nbsp; <a href="' . esc_url($base_url) . '">← Back to All Stats</a>';
		}
		
		echo $range_msg . '.</strong></p>';
	}

}